# 使用 Ubuntu 镜像
FROM ubuntu:24.10

# 设置维护者信息
LABEL maintainer="tangppiao@gmail.com"
LABEL version="latest"
LABEL description="安装启动ssh的Ubuntu镜像"

USER root

# 更新包列表并安装 OpenSSH 服务器
RUN apt-get update && \
    apt-get install -y openssh-server && \
    apt-get install -y sudo && \
    mkdir /var/run/sshd

# 设置 root 用户的密码
RUN echo "root:123456" | chpasswd
# 允许 root 用户通过 SSH 登录 修改的是ssh的配置文件
RUN sed -i "s/#PermitRootLogin prohibit-password/PermitRootLogin yes/" /etc/ssh/sshd_config
# 允许 root 用户使用 sudo 这一步可能使用其他用户名用得上o
RUN echo "root  ALL=(ALL)    ALL" >> /etc/sudoers
# 生成ssh公钥 密码为空
RUN ssh-keygen -t rsa -f "/root/.ssh/id_rsa" -P "" && \
    cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys && \
    chmod 0600 ~/.ssh/authorized_keys
 
# 拷贝启动脚本到容器
COPY ./ssh_entrypoint.sh /root/ssh_entrypoint.sh
RUN chmod +x /root/ssh_entrypoint.sh

# 暴露 SSH 端口
EXPOSE 22

# 使用 ENTRYPOINT 指定启动脚本
ENTRYPOINT ["/root/ssh_entrypoint.sh"]
# 保持容器始终运行
CMD ["tail", "-f","/dev/null"]

