FROM ubuntu:24.10
# 这个dockersfile是搭建伪分布式的Hadoop的镜像，包含ssh设置
#
# 设置维护者信息
LABEL maintainer="tangppiao@gmail.com"
LABEL version="latest"
LABEL description="伪分布Hadoop"

USER root

ENV HADOOP_HOME="/opt/hadoop"
ENV HADOOP_CONF_DIR="$HADOOP_HOME/etc/hadoop"
ENV HADOOP_LOG_DIR="/var/log/hadoop"
ENV PATH="$HADOOP_HOME/hadoop/sbin:$HADOOP_HOME/bin:$PATH"

# 更新包列表并安装 OpenSSH 服务器
RUN apt-get update && \
    apt-get install -y openssh-server && \
    apt-get install -y sudo && \
    mkdir /var/run/sshd

# 设置 root 用户的密码
RUN echo "root:123456" | chpasswd
# 允许 root 用户通过 SSH 登录 修改的是ssh的配置文件
RUN sed -i "s/#PermitRootLogin prohibit-password/PermitRootLogin yes/" /etc/ssh/sshd_config
# 允许 root 用户使用 sudo 这一步可能使用其他用户名用得上o
RUN echo "root  ALL=(ALL)    ALL" >> /etc/sudoers
# 生成ssh公钥 密码为空
RUN ssh-keygen -t rsa -f "/root/.ssh/id_rsa" -P "" && \
    cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys && \
    chmod 0600 ~/.ssh/authorized_keys

# 暴露 SSH 端口
EXPOSE 22

WORKDIR /opt

# 下载JAVA和Hadoop
RUN apt-get install -y openjdk-11-jdk 

# 这里可以自己下下来也可以用命令下载
ADD hadoop-3.4.0.tar.gz /opt/
#RUN wget https://dlcdn.apache.org/hadoop/common/hadoop-3.4.0/hadoop-3.4.0.tar.gz && \
#RUN tar -xzvf hadoop-3.4.0.tar.gz  && \
RUN mv hadoop-3.4.0 hadoop && \
    rm -rf hadoop-3.4.0.tar.gz && \
    mkdir /var/log/hadoop #存放log

# 复制配置文件
COPY  config_single/* /tmp/

RUN mv /tmp/core-site.xml $HADOOP_CONF_DIR/core-site.xml && \
    mv /tmp/hadoop-env.sh $HADOOP_CONF_DIR/hadoop-env.sh && \
    mv /tmp/hdfs-site.xml $HADOOP_CONF_DIR/hdfs-site.xml 
    
RUN chmod +x $HADOOP_HOME/sbin/start-dfs.sh && \
    chmod +x $HADOOP_HOME/sbin/start-yarn.sh 

# 初始化HDFS
RUN hdfs namenode -format

# 拷贝启动脚本到容器
COPY ./hadoop_single_entrypoint.sh /root/hadoop_single_entrypoint.sh
RUN chmod +x /root/hadoop_single_entrypoint.sh

# 使用 ENTRYPOINT 指定启动脚本
ENTRYPOINT ["/root/hadoop_single_entrypoint.sh"]
# 运行HDFS
CMD ["tail", "-f","/dev/null"]
